import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
// import Details from '../components/details'
import Initial from '../components/initial'
import getLinkData from '../helpers/getLinkData'
import styles from '../styles/Common.module.scss'

import dynamic from 'next/dynamic'
import { Suspense } from 'react'

const Details = dynamic(() => import('../components/details'), {
  suspense: true,
})

const Home: NextPage = () => {
  const [link, setLink] = useState<string | null>(null);
  const [linkData, setLinkData] = useState<any | null>(null);
  // console.log()
  useEffect(() => {
    (async () => {
      if (link) {
        const data = await getLinkData(link);
        if (data) {
          setLinkData(data)
        }
      }
    })();
  }, [link])

  function reset(): void {
    setLink(null)
    setLinkData(null)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={'true'} />
        <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        {link !== null && linkData ?
          <>
            {typeof window !== undefined &&
              <Suspense fallback={`Loading...`}>
                <Details link={link} linkData={linkData} reset={reset} />
              </Suspense>
            }
          </>

          :
          <Initial setLink={setLink} />
        }
      </main>

      <footer className={styles.footer}>
        Designed and Developed by
        <a
          href="https://anishroy.me"
          target="_blank"
          rel="noopener noreferrer"
        > Anish Roy
        </a>
      </footer>
    </div>
  )
}

export default Home
